version: "3"

services:
  postgres:
    image: postgres:12.7
    container_name: postgresql_database
    networks:
      - formula1_network
    ports:
      - ${DESTINATION_DB_PORT}:${DESTINATION_DB_PORT}
    environment:
      - POSTGRES_USER=${DESTINATION_DB_USER}
      - POSTGRES_PASSWORD=${DESTINATION_DB_PASSWORD}
      - POSTGRES_DB=${DESTINATION_DB_DATABASE}
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
  create_tables:
    build: ./create_tables/
    image: create_tables:1.0
    container_name: create_tables_sh
    networks:
      - formula1_network
    environment:
      - USER=${DESTINATION_DB_USER}
      - PASSWORD=${DESTINATION_DB_PASSWORD}
      - HOST=${DESTINATION_DB_HOST}
      - DATABASE=${DESTINATION_DB_DATABASE}
  load_data:
    build: ./load_data/
    image: load_data:1.0
    container_name: load_data_py
    networks:
      - formula1_network
    environment:
      - destination_db=${DESTINATION_DB_TYPE}://${DESTINATION_DB_USER}:${DESTINATION_DB_PASSWORD}@${DESTINATION_DB_HOST}/${DESTINATION_DB_DATABASE}
      - origin_db=${ORIGIN_DB_TYPE}://${ORIGIN_DB_USER}:${ORIGIN_DB_PASSWORD}@${ORIGIN_DB_HOST}/${ORIGIN_DB_DATABASE}
    volumes:
      - ./data:/home/app/data
      - ./classes:/home/app/classes
  api:
    build: ./api/
    image: api:1.0
    container_name: ${API_NAME}
    networks:
      - formula1_network
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./classes:/home/app/classes
  dashboard:
    build: ./dashboard/
    image: dashboard:1.0
    container_name: dashboard_py
    networks:
      - formula1_network
    ports:
      - 8501:8501
    environment:
      - api_url=http://${API_NAME}:${API_PORT}/get-table/
    volumes:
      - ./classes:/home/app/classes
networks:
  formula1_network:
    driver: bridge