version: "3"

services:
  postgres:
    image: postgres:12.7
    container_name: postgresql_database
    networks:
      - formula1_network
    ports:
      - ${DESTINATION_DB_PORT}:${DESTINATION_DB_PORT}
    environment:
      - POSTGRES_USER=${DESTINATION_DB_USER}
      - POSTGRES_PASSWORD=${DESTINATION_DB_PASSWORD}
      - POSTGRES_DB=${DESTINATION_DB_DATABASE}
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
  create_tables:    
    build: ./src/create_tables/
    container_name: create_tables_sh
    networks:
      - formula1_network
    environment:
      - USER=${DESTINATION_DB_USER}
      - PASSWORD=${DESTINATION_DB_PASSWORD}
      - HOST=${DESTINATION_DB_HOST}
      - DATABASE=${DESTINATION_DB_DATABASE}
  load_data:    
    build: ./src/load_data/
    container_name: load_data_py
    networks:
      - formula1_network
    environment:
      - destination_db=${DESTINATION_DB_TYPE}://${DESTINATION_DB_USER}:${DESTINATION_DB_PASSWORD}@${DESTINATION_DB_HOST}/${DESTINATION_DB_DATABASE}
      - origin_db=${ORIGIN_DB_TYPE}://${ORIGIN_DB_USER}:${ORIGIN_DB_PASSWORD}@${ORIGIN_DB_HOST}/${ORIGIN_DB_DATABASE}
    volumes:
      - ./data:/home/app/data
networks:
  formula1_network:
    driver: bridge